import { InMemoryDbService } from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    let heroes = [
      {id: 11, name: 'Mr. Nice'},
      {id: 12, name: 'Narco'},
      {id: 13, name: 'Bombasto'},
      {id: 14, name: 'Celeritas'},
      {id: 15, name: 'Magneta'},
      {id: 16, name: 'RubberMan'},
      {id: 17, name: 'Dynama'},
      {id: 18, name: 'Dr IQ'},
      {id: 19, name: 'Magma'},
      {id: 20, name: 'Tornado'}
    ];

    let images = [
      {"product_number":"P1S","product_release":"17B","software_version":"R3A249"},
      {"product_number":"P1S","product_release":"17B","software_version":"R3A187"},
      {"product_release":"17B","software_version":"R3A187"},
      {"product_number":"P1S","product_release":"17B","software_version":"R3A172"},
      {"product_number":"P1S","product_release":"16B","software_version":"R2C17"},
      {"product_number":"P1S","product_release":"16A","software_version":"R1L42"},
      {"product_number":"P1S","product_release":"17B","software_version":"R3A155"},
      {"product_number":"P1S","product_release":"17B","software_version":"R3A129"},
      {"product_release":"17B","software_version":"R3A129"},
      {"product_number":"P1S","product_release":"17B","software_version":"R3A120"}
      ];

    let regItems = [
      {"duration":"11.16","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"System_Test","featureName":"L2VPN","id":7020,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_Regression_CBCST_UC2_LDP_NT/9/","jobStartPlan":"WK5","passedCase":71,"regType":"weekly","status":1,"targetTotalTC":71,"team":"17B_Regression_CBCST_UC2_LDP_NT","totalCase":71},
      {"duration":"0","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"L3","featureName":"IPv6 Unicast","id":7021,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_pacific_reg/11/","jobStartPlan":"WK23","passedCase":0,"regType":"weekly","status":1,"targetTotalTC":265,"team":"17B_regression_pacific_reg","totalCase":0,"utb":"UTB15"},
      {"duration":"1.58","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"OAM","featureName":"Chassis_Mgmt/SNMP/NTP/Licence/TS/Inventory","id":7022,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_crius_reg/8/","jobStartPlan":"WK05","passedCase":190,"regType":"weekly","status":1,"targetTotalTC":190,"team":"17B_regression_crius_reg","totalCase":190,"utb":"UTBcrius"},
      {"duration":"0.11","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"System_Test","featureName":"L3VPN","id":7023,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_Regression_CBCST_IPRAN_NT_P1S/9/","jobStartPlan":"WK5","passedCase":0,"regType":"weekly","status":1,"targetTotalTC":64,"team":"17B_Regression_CBCST_IPRAN_NT_P1S","totalCase":0},
      {"duration":"0","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"System_Test","featureName":"L3VPN","id":7024,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_Regression_CBCST_IPRAN_CT_P1S/7/","jobStartPlan":"WK5","passedCase":0,"regType":"weekly","status":1,"targetTotalTC":26,"team":"17B_Regression_CBCST_IPRAN_CT_P1S","totalCase":0},
      {"duration":"2.0","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"Feature_Test","featureName":"VPN_license","id":7025,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_Regression_L2VPN_L3VPN_License_Feature/3/","jobStartPlan":"WK38","passedCase":29,"regType":"weekly","status":1,"targetTotalTC":29,"team":"17B_Regression_L2VPN_L3VPN_License_Feature","totalCase":29},
      {"duration":"0.88","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"L3","featureName":"GDL/URPF","id":7026,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_winnower_reg/7/","jobStartPlan":"WK05","passedCase":3,"regType":"weekly","status":1,"targetTotalTC":4,"team":"17B_regression_winnower_reg","totalCase":4,"utb":"UTB03"},
      {"duration":"1.26","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"L2","featureName":"Y1731, Port Mirroring, L2ACL","id":7027,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/lmf_test_reg_fa_l2_hltapi_p1s/75/","jobStartPlan":"W39","passedCase":72,"regType":"weekly","status":1,"targetTotalTC":72,"team":"lmf_test_reg_fa_l2_hltapi_p1s","totalCase":72},
      {"duration":"2.32","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"L2","featureName":"PORT_LAG","id":7028,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_caliburn_reg/5/","jobStartPlan":"WK5","passedCase":67,"regType":"weekly","status":1,"targetTotalTC":170,"team":"17B_regression_caliburn_reg","totalCase":72,"utb":"UTB10"},
      {"comments":"","duration":"10.09","endDate":"2016-10-28","exceptionTestScript":1,"failedCase":4,"featureArea":"L3","featureName":"IPv6 Multicast","id":7029,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_atlantic_reg/7/","jobStartPlan":"WK04","newIssue":"","passedCase":79,"regType":"weekly","status":0,"targetTotalTC":82,"team":"17B_regression_atlantic_reg","totalCase":79,"utb":"UTB16"},
      {"duration":"1.42","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"L3","featureName":"PBR","id":7030,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/lmf_test_reg_fa_l3_hltapi_p1s/57/","jobStartPlan":"W39","passedCase":29,"regType":"weekly","status":1,"targetTotalTC":29,"team":"lmf_test_reg_fa_l3_hltapi_p1s","totalCase":29},
      {"duration":"2.94","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"L2","featureName":"L2ACL,mac_swap","id":7031,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/lmf_test_reg_fa_l2_p1s/143/","jobStartPlan":"W39","passedCase":116,"regType":"weekly","status":1,"targetTotalTC":116,"team":"lmf_test_reg_fa_l2_p1s","totalCase":116},
      {"duration":"0.97","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"L3","featureName":"ACL","id":7032,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/lmf_test_reg_fa_l3_p1s/190/","jobStartPlan":"W39","passedCase":57,"regType":"weekly","status":1,"targetTotalTC":58,"team":"lmf_test_reg_fa_l3_p1s","totalCase":58},
      {"duration":"4.97","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"OAM","featureName":"User Mgmt/AAA/Netconf/Release upgrade/BFD/SNMP","id":7033,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_atlas_titan_ymir_reg/5/","jobStartPlan":"WK5","passedCase":201,"regType":"weekly","status":1,"targetTotalTC":211,"team":"17B_regression_atlas_titan_ymir_reg","totalCase":204,"utb":"UTB02"},
      {"comments":"","duration":"9.25","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"OAM","featureName":"AdvancedNetconf_PM","id":7034,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_st_AdvancedNetconf_PM_reg/5/","jobStartPlan":"WK18","newIssue":"Known TR,HV27260,2;","passedCase":197,"regType":"weekly","status":0,"targetTotalTC":199,"team":"17B_regression_st_AdvancedNetconf_PM_reg","totalCase":199},
      {"comments":"","duration":"5.0","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"System_Test","featureName":"L3VPN","id":7035,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_CBCST_MPLS_TE_NT/11/","jobStartPlan":"WK8","newIssue":"Hot TR,HV28438,1;","passedCase":42,"regType":"weekly","status":0,"targetTotalTC":43,"team":"17B_regression_CBCST_MPLS_TE_NT","totalCase":43},
      {"duration":"2.02","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"Qos","featureName":"Qos PMM, Qos Propagation","id":7036,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/lmf_test_reg_fa_qos_hltapi_p1s/59/","jobStartPlan":"W39","passedCase":84,"regType":"weekly","status":1,"targetTotalTC":87,"team":"lmf_test_reg_fa_qos_hltapi_p1s","totalCase":87},
      {"duration":"0.6","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"Platform","featureName":"Qos PMM, Qos Propagation","id":7037,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/lmf_test_reg_fa_platform_hltapi_p1s/49/","jobStartPlan":"W39","passedCase":10,"regType":"weekly","status":1,"targetTotalTC":10,"team":"lmf_test_reg_fa_platform_hltapi_p1s","totalCase":10},
      {"comments":"There are 2 ptp-port connections on the both nodes, one is slave and the other is passive, shutdown the first ptp-port, then check the ptp clock status,  ptp clock status is incorrect.\nexpected result: locked\nreal result: holdover","duration":"5.93","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"Sync","featureName":"1588","id":7038,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_pine_reg/9/","jobStartPlan":"WK5","newIssue":"","passedCase":115,"regType":"weekly","status":0,"targetTotalTC":117,"team":"17B_regression_pine_reg","totalCase":117,"utb":"UTB16"},
      {"comments":"AdmnACL: 5 TCs failed due to TC problems in checking VOQ counters.\nL2FilterACL: 3 TCs failed due to test env problems, 1 TC failed due to TC problem (XC group was not deleted)\n","duration":"7.1","endDate":"2016-10-28","exceptionTestScript":0,"failedCase":0,"featureArea":"L2","featureName":"ACL/AdminACL/QosTM/L2FilterACL/MacSwap/Dot1q/QosPropagation/PortMirroring","id":7039,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/lmf_test_reg_jcat_p1s/351/","jobStartPlan":"WK5","newIssue":"","passedCase":393,"regType":"weekly","status":1,"targetTotalTC":427,"team":"lmf_test_reg_jcat_p1s","totalCase":418},
      {"duration":"7.5","endDate":"2016-10-29","exceptionTestScript":0,"failedCase":0,"featureArea":"L2","featureName":"DHCP relay proxy/Client/XC/TWAMP","id":7040,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_bang_reg/5/","jobStartPlan":"WK8","passedCase":123,"regType":"weekly","status":1,"targetTotalTC":123,"team":"17B_regression_bang_reg","totalCase":123,"utb":"UTB07"},
      {"duration":"7.56","endDate":"2016-10-29","exceptionTestScript":0,"failedCase":0,"featureArea":"L3","featureName":"MCAST","id":7041,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_storm_reg/8/","jobStartPlan":"WK06","passedCase":110,"regType":"weekly","status":1,"targetTotalTC":110,"team":"17B_regression_storm_reg","totalCase":110,"utb":"UTB06"},
      {"duration":"7.9","endDate":"2016-10-29","exceptionTestScript":0,"failedCase":0,"featureArea":"L3","featureName":"BVI","id":7042,"image":{"product_number":"P1S","product_release":"17B","software_version":"R3A187"},"jobLink":"https://spr-jenkins.mo.sw.ericsson.se/job/17B_regression_007_reg/5/","jobStartPlan":"WK15","passedCase":101,"regType":"weekly","status":1,"targetTotalTC":122,"team":"17B_regression_007_reg","totalCase":102,"utb":"UTB08"}
      ];
    return {heroes};
  }
}


/*
Copyright 2016 Google Inc. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at http://angular.io/license
*/